# -*- coding: utf-8 -*-
# Ordered list of projects used by the home page and the prev/next links on project pages.
PROJECTS = [
    dict(slug="vtla", group="embodied",
         kind=("MSc dissertation · King’s College London · Franka + GelSight", "硕士毕业课题 · 伦敦国王学院 · Franka + GelSight"),
         title=("Vision–Tactile–Language–Action learning for robotic fabric sorting",
                "视觉-触觉-语言-动作（VTLA）学习用于机器人织物分拣"),
         q=("Can a robot that cannot see the difference between two garments feel it, explain it, and act on it?",
            "两件看起来几乎一样的衣物，机器人能否靠“摸”分辨出来，再用语言说清楚，并据此完成分拣？"),
         desc=("An end-to-end system on a Franka arm: a GelSight fingertip presses hanging garments, a ResNet-18 load estimator replaces the force sensor at run time (MAE 0.33 N on unseen fabrics), a QLoRA-tuned Qwen2.5-VL compares softness, thickness, elasticity and texture, and the arm ranks four garments, picks one and places it in a basket. π0.5 served as the VLA backbone explored for the action policy.",
               "在 Franka 机械臂上搭建的端到端系统：GelSight 指尖按压悬挂衣物，ResNet-18 力估计器在部署阶段取代力传感器（未见织物 MAE 0.33 N），QLoRA 微调的 Qwen2.5-VL 比较柔软度、厚度、弹性与纹理，机械臂对四件衣物排序、挑选并放入篮筐。动作策略以 π0.5 作为 VLA 骨干进行探索。"),
         stack="Franka Emika · GelSight Mini · Qwen2.5-VL-7B · QLoRA · π0.5 · PyTorch · ROS",
         media=("assets/video/vtla-demo.mp4", "assets/video/vtla-demo.jpg"), media_type="video",
         ),
    dict(slug="tactile-umi", group="embodied",
         kind=("Research system · joint work at KCL · π0.5 branch", "研究系统 · KCL 合作项目 · π0.5 分支"),
         title=("Tactile UMI: from hand-held visuotactile demonstrations to a π0.5 policy on a Franka FR3",
                "Tactile UMI：从手持视触觉示教到 Franka FR3 上的 π0.5 策略"),
         q=("How do hand-held demonstrations with touch become calibrated, auditable data a VLA policy can actually learn from?",
            "带触觉的手持示教，如何变成标定可靠、可审计、能真正训练 VLA 策略的数据？"),
         desc=("With a lab mate I built a UMI-style hand-held gripper with wrist RGB, dual GelSight fingertips, Quest motion tracking and gripper state; calibrated geometry and clocks (hand–eye, 56.7 ms Quest–camera offset, gripper-width lookup) and audited every episode. He trained a Diffusion Policy on the corpus; I fine-tuned π0.5 on the same demonstrations and ran it on the FR3.",
               "我和实验室同学一起搭建了带手腕相机、双 GelSight 指尖、Quest 运动追踪与夹爪状态的 UMI 式手持夹爪；完成几何与时钟标定（手眼标定、56.7 ms Quest–相机时延、夹爪开度查表），并对每条示教做审计。他用这批数据训练 Diffusion Policy，我则在同一批示教上微调 π0.5，并在 FR3 上实机运行。"),
         stack="UMI gripper · GelSight · Meta Quest · ArUco · π0.5 (openpi) · Franka FR3 · Zarr/H5",
         media=("assets/video/umi-pi05-demo.mp4", "assets/video/umi-pi05-demo.jpg"), media_type="video",
         ),
    dict(slug="tiago", group="embodied",
         kind=("Group project · KCL × Guy’s and St Thomas’ · ROS 2", "小组项目 · KCL × Guy’s and St Thomas’ 医院 · ROS 2"),
         title=("TIAGo assistive robot for chemotherapy wards", "医院辅助患者的 TIAGo 自主服务机器人"),
         q=("Can a ward robot notice a patient who needs help, reach them safely, and stay out of the way of clinical staff?",
            "病房里的机器人能否察觉需要帮助的患者、安全地走到他们身边，又不打扰医护工作？"),
         desc=("A ROS 2 + Webots system for the TIAGo platform: speech trigger (Faster-Whisper) followed by MediaPipe wave detection, RGB-D target localisation, and a full SLAM → AMCL → Nav2 pipeline that stops at a social stand-off distance. 92% end-to-end success and 94% navigation success over simulated ward trials.",
               "基于 TIAGo 平台的 ROS 2 + Webots 系统：语音触发（Faster-Whisper）后由 MediaPipe 检测挥手，RGB-D 定位患者，再经 SLAM → AMCL → Nav2 完整导航流水线，在社交安全距离处停下。病房仿真试验端到端成功率 92%，导航成功率 94%。"),
         stack="ROS 2 Humble · Webots · Nav2 · SLAM Toolbox · AMCL · MediaPipe · Faster-Whisper · Docker",
         media=("assets/video/tiago-demo.mp4", "assets/video/tiago-demo.jpg"), media_type="video",
         ),
    dict(slug="thread-inspection", group="industrial",
         kind=("Research assistant · Yangtze University · 2 SCI Q1 + 2 SPIE papers + 2 patents", "科研助理 · 长江大学 · 2 篇 SCI Q1 + 2 篇 SPIE + 2 项专利"),
         title=("Multi-vision and deep-learning inspection of internal threads", "基于多视觉与深度学习的内螺纹缺陷检测系统"),
         q=("How do you inspect a thread that lives inside a dark, curved, 100 mm bore, when defect samples are too rare to train on?",
            "螺纹藏在黑暗、弯曲的 100 mm 孔内，缺陷样本又极其稀少，如何做到自动检测？"),
         desc=("A six-fisheye ring probe with strip lighting, cylindrical-model panorama stitching where planar methods fail, DFMGAN few-shot defect synthesis, and YOLOv8 detection (mAP 91.6%). A robot-arm carrier cut acquisition time by 44%.",
               "六目鱼眼环形探头配条形光源；在平面拼接全部失效的曲面场景下提出柱面投影全景拼接；用 DFMGAN 少样本生成缺陷图像；YOLOv8 检测 mAP 91.6%。机械臂采集方案比步进电机方案提速 44%。"),
         stack="Raspberry Pi · fisheye cameras · OpenCV · SIFT/RANSAC · StyleGAN2/DFMGAN · YOLOv8",
         media=("assets/img/p4_robot_arm_rig_photo.png", None), media_type="img",
         ),
    dict(slug="gfrp-ml", group="industrial",
         kind=("Research assistant · Yangtze University · 2 SCI Q1 papers", "科研助理 · 长江大学 · 2 篇 SCI Q1 论文"),
         title=("Small-sample machine learning for engineering-structure modelling and optimisation",
                "小样本机器学习驱动的工程结构性能建模与优化"),
         q=("With only 72 destructive tests, can a model predict how a composite column will fail—and tell you how to design a better one?",
            "只有 72 组破坏性试验数据，模型能否预测复合材料柱的承载性能，并反过来指导设计？"),
         desc=("Genetic-algorithm data augmentation (72 → 15,000 virtual samples), a Reptile meta-learning regressor reaching R² 0.982 for ultimate bearing capacity and 0.955 for displacement, and a TPOT AutoML benchmark that yields concrete optimal section designs.",
               "遗传式数据增广（72 → 15,000 组虚拟样本）；基于 Reptile 的元学习回归模型，极限承载力 R² 0.982、极限位移 R² 0.955；TPOT AutoML 对比实验并反演出最优截面设计方案。"),
         stack="Python · scikit-learn · PyTorch · Reptile/MAML · TPOT AutoML · SVR/GPR/RBFNN",
         media=("assets/img/p5_meta_gfrp_columns_photo.jpg", None), media_type="img",
         ),
    dict(slug="industrial-monitoring", group="industrial",
         kind=("Research assistant · Yangtze University · 2 utility patents, first inventor", "科研助理 · 长江大学 · 2 项实用新型专利（第一发明人）"),
         title=("Machine-vision monitoring and early warning for hazardous well sites", "基于机器视觉的工业监测预警系统"),
         q=("On an open well site full of flammable gas, how do you catch a missing hard hat—and tell workers which way to run?",
            "在易燃易爆气体环境的井场上，如何自动发现没戴安全帽的工人，并在泄漏时告诉大家往哪跑？"),
         desc=("A three-axis (rotate / extend / pitch) camera gantry that sweeps the wellhead and flags missing hard hats and smoking on an embedded box, plus a solar-powered beacon that couples an H₂S detector with a wind vane so an LED arrow always points to the up-wind escape route.",
               "旋转/伸缩/俯仰三自由度视觉巡检机构，在嵌入式控制盒上识别未戴安全帽与吸烟行为；以及光伏供电的预警装置，把硫化氢检测与风向标联动，LED 箭头始终指向逆风逃生方向。"),
         stack="Embedded vision · stepper/servo mechanisms · MCU · H₂S sensing · solar power · patent drafting",
         media=("assets/img/p6_patent_wellhead_fig1_overall_tripod_camera.png", None), media_type="img", contain=True,
         ),
    dict(slug="hri30", group="internship",
         kind=("Internship · Snap Inc. Spectacles AR · ML engineering (CV) · London, 2026", "实习 · Snap Inc. Spectacles AR · 机器学习工程（CV 方向）· 伦敦 · 2026"),
         title=("Dual-stream action recognition for industrial human–robot collaboration (HRI30)",
                "面向工业人机协作的双流动作识别（HRI30）"),
         q=("Can RGB appearance and skeleton motion be fused so a robot reads what a worker is doing?",
            "把 RGB 外观与骨架运动融合，机器人能否读懂工人正在做什么？"),
         desc=("Two branches on the HRI30 dataset (30 industrial actions): a Kinetics-pretrained 3D ResNet-18 on 16-frame clips and a six-block ST-GCN on YOLOv8-Pose skeletons, fused by weighted late fusion. Built end to end—preprocessing, training, batched inference and submission tooling.",
               "在 HRI30 数据集（30 类工业动作）上搭建双分支：Kinetics 预训练的 3D ResNet-18 处理 16 帧片段，六层 ST-GCN 处理 YOLOv8-Pose 骨架序列，加权后期融合。从预处理、训练到批量推理与结果导出全链路独立完成。"),
         stack="PyTorch · torchvision r3d_18 · YOLOv8-Pose · ST-GCN · OpenCV · late fusion",
         media=("assets/img/hri30-dataset.jpg", None), media_type="img",
         ),
]

GROUPS = [
    ("embodied", "Embodied intelligence and robot learning", "具身智能与机器人学习", "King’s College London, 2025–2026", "伦敦国王学院，2025–2026"),
    ("industrial", "Industrial vision and data-driven engineering", "工业视觉与数据驱动工程", "Yangtze University, 2021–2025", "长江大学，2021–2025"),
    ("internship", "Internship", "实习经历", "Snap Inc., 2026", "Snap Inc.，2026"),
]
